AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'test/**/*'
    - 'Rakefile'
    - 'config.ru'

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
