# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6ff27464a4f6ef6be9eab5a6771527655428d2b121bbd2eddc2453d56ac256886e5585b53f9145e2cefd675c07337e0a13428a3d1a7f71d65f53ab1f844a0a02

test:
  secret_key_base: b6e2d8ad47b6f8b46cf219d620dbbe48c7688a31e9e448dc8195cd89dc48ab4eca708d675b5772b2333da005d0bb5bc468274e81490571c537a330ff54835bd2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
